### ISSUE TITLE
Add a Blog Page

### ISSUE THREAD

**Issue by ghislaineguerin** [mathesar-foundation/mathesar-website#88]
### Problem
As part of our ongoing efforts to improve communication and engagement with our users (see [Gather User Feedback](https://wiki.mathesar.org/en/projects/gather-user-feedback)), we need a dedicated space on our website where we can share updates, survey results, changelog info, and other relevant content.

### Proposed Solution
We will add a blog page to the Mathesar website and establish a process for creating and publishing blog posts. The blog page will include blog post listings with titles, brief excerpts, and publication dates, as well as individual post pages with full content. 

Even though at the moment we may not be able to produce highly sophisticated content, having this space will provide us with an opportunity to reach out to visitors and share important project updates.

### Reference
Here are a couple of examples of how other projects are using their blogs:

[NetBox Blog](https://netbox.dev/blog/) - They use their blog for posting surveys and changelog information. The content is concise and focused.
[Pulsar Edit Blog](https://pulsar-edit.dev/blog/) - They post detailed analysis of survey results, giving their users insights into the decisions being made based on the feedback received.

- [ ] Design the blog page layout
- [ ] Implement the blog page into the current Mathesar website

**Comment by anamika1804** [comment]
Hi @ghislaineguerin , hope you're doing well. I'd like to take this issue up, if you could assign me.

**Comment by kgodey** [comment]
@anamika1804 This issue is already in progress (see #89) and does not need further work.
