### ISSUE TITLE
[bug]:Drop-down menu on the navbar doesn't close on double click

### ISSUE THREAD

**Issue by Harsh-kumar-jha** [mathesar-foundation/mathesar-website#91]
## Description 
On the Navbar menu section, there are two drop-down items and when I tried to click it showed all the drop-down items but when I double click on them, it doesn't close.

## Expected behavior
When anyone double-taps on the drop-down menu, it should close automatically

## Step To Reproduce
1. Go to the website of mathesar.org
2. look for the nav menu
3. Now look for drop-down items.
4. Try to double-click on it

## Additional Context
https://github.com/centerofci/mathesar-website/assets/87357941/76a0102d-a2e3-494e-a8c5-86db0d8f735d

**Comment by kgodey** [comment]
Thanks for reporting this, @Harsh-kumar-jha.

**Comment by Moksh45** [comment]
Can you please assign this issue to me?
