### ISSUE TITLE
Old twitter logo present in the footer

### ISSUE THREAD

**Issue by Murdock9803** [mathesar-foundation/mathesar-website#99]
## Description
The footer of the website contains the old logo for X (previously twitter)

## Expectation
The logo should be replaced with the new X logo

## Screenshot
![Screenshot 2023-12-24 000221](https://github.com/mathesar-foundation/mathesar-website/assets/136724527/51b2cc6f-b906-4599-b258-316c1a985c00)

## Implementation
- [x] I would like to implement the feature

**Comment by kgodey** [comment]
@Murdock9803 thanks for reporting, please go ahead and submit a PR.

**Comment by Murdock9803** [comment]
@kgodey @seancolsen as my PR regarding this issue is merged, I am closing this issue. Thanks for the guidance.
